### ISSUE TITLE
RequiredIndicator is not shown on @NotEmpty fields

### ISSUE THREAD

**Issue by eiswind** [vaadin/vaadin-form-layout-flow#109] opened 2019-11-26 11:04 UTC
I created a little example based on the form starter to demonstrate it.

https://github.com/eiswind/vaadin-requiredindicator

```  <vaadin.version>14.0.14</vaadin.version>```

The changes I made are simple:

Create a Bean Property like 

```
    @NotEmpty
    @NotBlank
    public String getFirstname() {
        return firstname;
    }
```

Use a BeanValidator:
```
// Configure Form
        Binder<Employee> binder = new BeanValidationBinder<>(Employee.class);
```

Form should mark the field as required, but it does not.

**Comment by web-padawan** [comment] 2020-02-18 20:07
The repository is no longer available but the above comment explains what the problem was:

> It seems that the problem is on FormLayout's side as it doesn't happen with a lonely TextField.

This is not a bug, but rather a missing feature of `<vaadin-form-item>` component.

Closing as duplicate of https://github.com/vaadin/vaadin-form-layout/issues/122 (please see my comments there).

**Closed by web-padawan** 2020-02-18 20:07 UTC
Labels: bug
