### ISSUE TITLE
Required fields do not appear as required if 'pre filled'

### ISSUE THREAD

**Issue by knoobie** [vaadin/vaadin-form-layout-flow#66] opened 2018-10-09 09:49 UTC
DetailsView: 

On page load the Binder of the fields is configured with (binder.setReadOnly(true)) .
![readonly-true](https://user-images.githubusercontent.com/3968629/46661059-bec80280-cbb8-11e8-83ac-785493d4ea68.png)

User presses "edit". I set (binder.setReadOnly(false)) and I would expect that the required fields are shown for both (empty and already filled fields.) (blue/red mark next to the caption)
![readonly-false](https://user-images.githubusercontent.com/3968629/46661057-be2f6c00-cbb8-11e8-8ea7-430a0f1522fd.png)

After I remove the text / input from the first field it is shown as required. 
![after-clear-field](https://user-images.githubusercontent.com/3968629/46661056-be2f6c00-cbb8-11e8-878e-bc96a909db3a.png)

Fields should always have an visible indication that they are required. (Accessibility/Usability problem as well.)

**Comment by jouni** [comment] 2019-10-04 07:11
The required indicator behavior has indeed been implemented so that it disappears after the user has entered a value: https://github.com/vaadin/vaadin-lumo-styles/blob/master/mixins/required-field.html#L38-L51

See the selector for a required field without a value, where the opacity of the indicator is set to 1.

There was not a lot of thought behind this behavior. The only reasoning was that it would help reduce some visual clutter from the form, and make it easier to spot the fields that still need to be filled in.

But that’s not a good justification for it. The information which fields are/were required is most probably more important for the user.

So, I think we might want to change this behavior so that the required indicator is always visible. 

Additionally (outside the scope of this issue), I think it would be great to offer the choice between indicating optional fields in a form instead of the required fields.

**Comment by Haprog** [comment] 2019-10-04 07:16
> So, I think we might want to change this behavior so that the required indicator is always visible.

I agree.

Closing this issue as it's currently working as intended. But we should probably open a new issue in https://github.com/vaadin/vaadin-core/issues for updating the default behaviour (in all of our web components that implement the required indicator) of required indicator to be always visible (when field is set as required)

**Closed by Haprog** 2019-10-04 07:16 UTC
Labels: bug

**Comment by Haprog** [comment] 2019-10-04 07:41
Created an enhancement issue about this here: https://github.com/vaadin/vaadin-core/issues/223
