### ISSUE TITLE
FormLayout width depends on the number of rows it contains; goes to 100% with 3 or more rows

### ISSUE THREAD

**Issue by edler-san** [vaadin/vaadin-form-layout-flow#73] opened 2019-01-08 11:52 UTC
Follow up ticket for vaadin/flow/issues/4924  Please see description there.
Potentially related to #23

**Comment by pleku** [comment] 2019-01-21 08:31
Duplicate of https://github.com/vaadin/vaadin-form-layout/issues/103

**Closed by pleku** 2019-01-21 08:31 UTC
Labels: BFP, bug
