### ISSUE TITLE
Baseline problem with RadioButtonGroup

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-form-layout-flow#85] opened 2019-04-16 20:40 UTC
Tested with Vaadin 13.0.3 / vaadin-form-layout-flow 1.3.1
With the following code:
```
@Route("")
public class MainView extends VerticalLayout {
	public MainView() {
		HorizontalLayout layout = new HorizontalLayout();
		layout.setJustifyContentMode(JustifyContentMode.BETWEEN);
		layout.setDefaultVerticalComponentAlignment(Alignment.CENTER);
		FormLayout form = new FormLayout();

		ComboBox<String> combobox1 = new ComboBox<String>();
		combobox1.setItems("Option 1", "Option 2", "Option 3");
		combobox1.setValue("Option 1");
		form.addFormItem(combobox1, "ComboBox 1");

		Checkbox checkbox1 = new Checkbox();
		form.addFormItem(checkbox1, "Checkbox 1");

		RadioButtonGroup<String> radioButton1 = new RadioButtonGroup<String>();
		radioButton1.setItems("Option 1", "Option 2", "Option 3");
		radioButton1.setValue("Option 1");
		radioButton1.setEnabled(false);
		form.addFormItem(radioButton1, "Radio button 1");

		LocalDate date1 = LocalDate.now();
		DatePicker datePicker1 = new DatePicker(date1);
		form.addFormItem(datePicker1, "Date 1");

		layout.add(form);
		add(layout);
	}
}
```
There is a baseline problem only with the RadioButtonGroup as it can be seen in the following picture:

![BaseLineProblem](https://user-images.githubusercontent.com/28312758/56242441-ac9ab580-606e-11e9-93b0-294e537deda1.png)

**Comment by web-padawan** [comment] 2020-02-14 09:47
Closing as duplicate of vaadin/vaadin-radio-button#106.

**Closed by web-padawan** 2020-02-14 09:47 UTC
