### ISSUE TITLE
adding attribute 'label-position' has no effect

### ISSUE THREAD

**Issue by riandree** [vaadin/vaadin-form-layout-flow#40] opened 2018-06-01 08:46 UTC
i am trying to set the attribute _'label-position'_ in order to have the label positioned
on top of an item. Unfortunately setting the attribute named _'label-position'_ does not
yield the expected attribute on the _<form-item>_ Element. 
If i do the same with a random attribute, e.g. '_loremipsum_', the attribute appears on the 
_<form-item>_ element.

```
 FormItem formItem = new FormItem(new Label("Label"),cronGrid);
 formItem.getElement().setAttribute("label-position", "top");
 formItem.getElement().setAttribute("loremipsum", "top");
```

manually setting the **label-position="top"** on the rendered element has the expected effect.
i suppose it is not the expected behaviour to ignore label-position attributes set from the java side ?

**Comment by BarneyIt** [comment] 2019-03-29 17:21
Just an info: probably I've found similar trouble on Vaadin 13.0.2; so this means that this issue is still open ?

**Comment by web-padawan** [comment] 2020-02-14 09:24
Closing as duplicate of vaadin/vaadin-form-layout#42 which describes why it happens.

**Closed by web-padawan** 2020-02-14 09:24 UTC
Labels: bug, component, investigation
