### ISSUE TITLE
FormItem position and value issues when setting visibility

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-form-layout-flow#92] opened 2019-05-09 05:06 UTC
@martinisraelsen commented on [Thu Aug 16 2018](https://github.com/vaadin/flow/issues/4530)

Have a form with FormItems. The FormItems are set to be visible/invisible based on user selection(s). For example, if the user selects "address" the FormItem with the address field is set to visible and the phone number is set to invisible. If the user selects "phone" the address field is set to invisible and the phone number is set to visible.

Changing visible this way causes several problems:

- FormItem Label is missing
- Component placeholder text is missing
- Label and Component is not aligned with other FormItems labels and components
- Component value is missing or not displayed.

This issue exists in V10 and V11 alpha 1 and beta 1.

Source code and video clip attached
<img width="347" alt="formitemissue" src="https://user-images.githubusercontent.com/6271003/44178003-fda87300-a0b5-11e8-9c81-6b4eda278d8e.png">
[FormItemIssue.zip](https://github.com/vaadin/flow/files/2291969/FormItemIssue.zip)

---

@martinisraelsen commented on [Sun Apr 14 2019](https://github.com/vaadin/flow/issues/4530#issuecomment-483041316)

This issue also exists in V12 and V13 all the way to V13.0.3. I have verified that the issue occurs in the major browsers (Safari, Firefox, Chrome).

To reproduce:
Run the attached file with Jetty:run and open your browser.

- Click "Add Customer"
- Change "Type" to "User"
- Hidden fields are being shown and they are not aligned. Resizing the window realigns the fields correctly.

<img width="921" alt="Screen Shot 2019-04-14 at 1 51 07 PM" src="https://user-images.githubusercontent.com/6271003/56097679-563a4500-5ebd-11e9-82c2-762772d970e9.png">
<img width="939" alt="Screen Shot 2019-04-14 at 1 51 20 PM" src="https://user-images.githubusercontent.com/6271003/56097683-5afef900-5ebd-11e9-9192-df3ae69330cb.png">

[Vaadin-Appstarter.zip](https://github.com/vaadin/flow/files/3077766/Vaadin-Appstarter.zip)

The same app demo can also be used to provoke the missing fields in Safari (https://github.com/vaadin/flow/issues/5446)

---

@martinisraelsen commented on [Sun Apr 14 2019](https://github.com/vaadin/flow/issues/4530#issuecomment-483042465)

Note: It looks like it may be caused by the fields being set to not visible before being shown. If you "Add User" which has all fields visible, they will show up correctly. 

When you "Add Customer", some fields (FormItems) are set to not visible and when they later are set to visible (e.g. by changing the type) their position is off.

---

@martinisraelsen commented on [Wed Apr 24 2019](https://github.com/vaadin/flow/issues/4530#issuecomment-486216386)

Also noticed the issue in the Flow Project Wizard (https://labs.vaadin.com/project-wizard/) on an iPad. Notice that the form fields are jumbled together at the top.

![IMG_0007](https://user-images.githubusercontent.com/6271003/56660938-401f4800-6666-11e9-9575-dfda88cb61b7.jpg)

---

@martinisraelsen commented on [Wed May 08 2019](https://github.com/vaadin/flow/issues/4530#issuecomment-490612845)

@denis-anisimov Should this issue be logged in https://github.com/vaadin/vaadin-form-layout? If so are you able to move it over?

**Comment by martinisraelsen** [comment] 2019-05-17 17:18
Update: It's still happening in 13.0.7. I also noticed that the layout issue also seems to happen in form layouts that don't change the visibility of the elements.

**Comment by Haprog** [comment] 2019-05-31 11:32
I'm pretty sure this is a duplicate of vaadin/vaadin-form-layout#110. We'll probably have a fix for that pretty soon.

**Comment by Haprog** [comment] 2019-06-03 11:09
Fix for vaadin/vaadin-form-layout#110 has been released in `vaadin-form-layout` [v2.1.3](https://github.com/vaadin/vaadin-form-layout/releases/tag/v2.1.3). The webjar for it should appear in Maven central soon.

**Comment by Haprog** [comment] 2019-06-03 11:59
New webjar now in Maven central.

I was able to reproduce the issue also with https://labs.vaadin.com/project-wizard/ and when I run that project locally with an updated dependency of `vaadin-form-layout` the issue doesn't appear anymore, so this seems to be fixed now.

The fixed version should be included to next maintenance releases of Vaadin 13 and Vaadin 14 but in the meanwhile you can pin this dependency to your `pom.xml` to use the latest version with the fix:

```xml
<dependency>
    <groupId>org.webjars.bowergithub.vaadin</groupId>
    <artifactId>vaadin-form-layout</artifactId>
    <version>2.1.3</version>
</dependency>
```

**Closed by Haprog** 2019-06-03 11:59 UTC
Labels: BFP, bug

**Comment by Haprog** [comment] 2019-06-18 12:06
I just realized part of this issue (original description) probably was what is now described in vaadin/vaadin-form-layout-flow#102. So if you are toggling visibility of items in a form layout you probably need to call `updateStyles` method to make everything behave as it should. See my comment here: https://github.com/vaadin/vaadin-form-layout-flow/issues/102#issuecomment-503072582

**Comment by martinisraelsen** [comment] 2019-06-18 15:13
@Haprog I tried the updated webjar and it does seem to solve the issue - even without calling updateStyles. I did notice one form layout that still has a slight problem, but it's nested within another formlayout. I seem to remember I read somewhere that it's not a supported use case, so I'll try to refactor it not be nested. 

Thanks for your help!

**Comment by zanonmark** [comment] 2019-07-22 22:56
I confirm the issue on 14.0.0rc6: calling updateStyles solves the problem, while pinning the vaadin-form-layout to version 2.1.3 does not.

Thanks,
MZ

**Comment by web-padawan** [comment] 2019-07-23 06:03
@zanonmark vaadin/vaadin-form-layout#110 was the issue specific to Safari.

At the moment, calling `updateStyles` is a necessary step when toggling visibility of the items.
This happens because we don't yet have mechanism to track visibility changes.

See also the issue where the suggested fix for Flow is requested: https://github.com/vaadin/vaadin-form-layout/issues/116
