### ISSUE TITLE
AddFormItem should form a connection between label and component for accessibility reasons

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-form-layout-flow#86] opened 2019-04-22 18:56 UTC
Doing `form.addFormItem(firstName, "First Name");` adds a component and a label into the form layout. However, these to tags are not connected with each others and accessibility tools like axe and lighthouse complain about fields without labels. Form layout should use `label.setFor(component);` to make a connection between the two, and serve screenreaders better.

**Comment by web-padawan** [comment] 2020-02-13 16:16
Closing as duplicate of vaadin/vaadin-form-layout#74 because it's more than `for` attribute.

**Closed by web-padawan** 2020-02-13 16:16 UTC
